language: bash
os:
    - linux
    - osx
before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update && sudo apt-get install -y git-core; fi
    - if [ $TRAVIS_OS_NAME = osx ]; then brew upgrade git; fi
script:
    - bash -i ./test/suite.sh
