---
jobs:
- name: test-ubuntu
  public: true
  serial: true
  plan:
  - get: resource-bashlib
    trigger:    true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/ubuntu-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci.sh']
- name: test-debian
  public: true
  serial: true
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/debian-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci.sh']
- name: test-fedora
  public: true
  serial: true
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/fedora-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci.sh']
- name: test-opensuse
  public: true
  serial: true
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/opensuse-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci.sh']
- name: test-centos
  public: true
  serial: true
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/centos-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci.sh']

resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true
