---
platform: linux
image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: test-result

outputs:
- name: release-result

run:
  path: sh
  args: ['./resource-bashlib/ci/scripts/release-github.sh']
