---
resources:
- name:                 resource-bashlib
  type:                 git
  source:
    uri:                git@github.com:vergissberlin/bashlib.git
    branch:             master
    private_key:        ((github-private-key))
- name:                 github-release
  type:                 github-release
  source:
    user:               vergissberlin
    repository:         bashlib
    access_token:       ((github-token))
- name:                 slack
  type:                 slack-notification
  source:
    url:                ((slack-hook-url))

resource_types:
- name:                 slack-notification
  type:                 docker-image
  source:
    repository:         cfcommunity/slack-notification-resource
    tag:                latest
- name:                 resource-version
  type:                 semver
  source:
    driver:             git
    initial_version:    0.0.1
    uri:                ((git-uri-bump-semver))
    branch:             version
    file:               version
    private_key:        ((github-private-key))

jobs:
- name:                 tag
  plan:
  - get:                github-release
    trigger:            true
  - put:                github-release
    params:
      repository:       resource-bashlib
      tag:              resource-bashlib/VERSION
      tag_prefix:       v

- name:                 test
  public:               true
  plan:
  - get:                resource-bashlib
    trigger:            true
  - aggregate:
    - task:             task-test-alpine
      file:             resource-bashlib/ci/tasks/test-alpine.yml
    - task:             task-test-centos
      file:             resource-bashlib/ci/tasks/test-centos.yml
    - task:             task-test-debian
      file:             resource-bashlib/ci/tasks/test-debian.yml
    - task:             task-test-fedora
      file:             resource-bashlib/ci/tasks/test-fedora.yml
    - task:             task-test-opensuse
      file:             resource-bashlib/ci/tasks/test-opensuse.yml
    - task:             task-test-ubuntu
      file:             resource-bashlib/ci/tasks/test-ubuntu.yml
- name:                 release
  public:               true
  plan:
  - get:                resource-bashlib
    trigger:            true
    passed:             [test]
  - put:                github-release
    params:
      repository:       bashlib
      tag:              bashlib/VERSION
      tag_prefix:       v
  - aggregate:
    - task:            task-release-github
      file:            resource-bashlib/ci/tasks/release-github.yml
  on_success:
    put:                slack
    params:
      username:         ((message-username))
      icon_emoji:       ((message-success-emoji))
      text:             ((message-success-text))
  on_failure:
    put:                slack
    params:
      username:         ((message-username))
      icon_emoji:       ((message-fail-emoji))
      text:             ((message-fail-text))
