---
resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

jobs:
- name: test-alpine
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    file:
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/alpine-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-centos
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-alpine]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/centos-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-debian
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-centos]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/debian-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-fedora
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-debian]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/fedora-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-opensuse
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-fedora]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/opensuse-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed on fedora"
- name: test-ubuntu
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-opensuse]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/ubuntu-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_success:
    put: slack-alert
    params:
      text: "bashlib: Test successfully"
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
