---
resources:
- name:              resource-bashlib
  type:              git
  source:
    uri:             https://github.com/vergissberlin/bashlib.git
    branch:          master
    private_key:     {{github-private-key}}
    disable_ci_skip: true
- name:              github-release
  type:              github-release
  source:
    access_token:    {{github-release-access-token}}
    repository:      github-release-concourse-test
    user:            vergissberlin



- name:              slack-alert
  type:              slack-notification
  source:
    url:             {{slack-hook-url}}
- name:              gh-release
  type:              github-release
  source:
    owner:           vergissberlin
    repository:      bashlib
    access_token:    64f25f6633c2052347233d3838b95744802a2596

resource_types:
- name:              slack-notification
  type:              docker-image
  source:
    repository:      cfcommunity/slack-notification-resource
    tag:             latest

jobs:
- name:              test
  public:            true
  plan:
  - get:             resource-bashlib
    trigger:         true
  - aggregate:
    - task:          task-test-alpine
      file:          resource-bashlib/ci/tasks/test-alpine.yml
    - task:          task-test-centos
      file:          resource-bashlib/ci/tasks/test-centos.yml
    - task:          task-test-debian
      file:          resource-bashlib/ci/tasks/test-debian.yml
    - task:          task-test-fedora
      file:          resource-bashlib/ci/tasks/test-fedora.yml
    - task:          task-test-opensuse
      file:          resource-bashlib/ci/tasks/test-opensuse.yml
    - task:          task-test-ubuntu
      file:          resource-bashlib/ci/tasks/test-ubuntu.yml
  on_success:
    put:             slack-alert
    params:
      username:      {{message-username}}
      icon_emoji:    {{message-success-emoji}}
      text:          {{message-success-text}}
  on_failure:
    put:             slack-alert
    params:
      username:      {{message-username}}
      icon_emoji:    {{message-fail-emoji}}
      text:          {{message-fail-text}}
- name:              release
  public:            true
  plan:
  - get:             resource-bashlib
    trigger:         true
    passed:          [test]
  - put:             gh-release
    params:
      name:          release-result/releases/name
      tag:           release-result/releases/tag
  - aggregate:
    - task:          task-release-github
      file:          resource-bashlib/ci/tasks/release-github.yml
  on_success:
    put:             slack-alert
    params:
      username:      {{message-username}}
      icon_emoji:    {{message-success-emoji}}
      text:          {{message-success-text}}
  on_failure:
    put:             slack-alert
    params:
      username:      {{message-username}}
      icon_emoji:    {{message-fail-emoji}}
      text:          {{message-fail-text}}
