---
resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

jobs:
- name: test-alpine
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
  - task: run-test
    file:
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/alpine-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-centos
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-alpine]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/centos-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-debian
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-centos]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/debian-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-fedora
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-debian]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/fedora-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
- name: test-opensuse
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-fedora]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/opensuse-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed on fedora"
- name: test-ubuntu
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-opensuse]
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vergissberlin/ubuntu-development}
      inputs:
      - name: resource-bashlib
      run:
        path: sh
        args: ['./resource-bashlib/ci/scripts/run.sh']
  on_success:
    put: slack-alert
    params:
      channel: "#transformers"
      username: "concourse ci"
      icon_url: https://media-api.atlassian.io/file/c34cd337-2a4b-4361-a5cd-ae5a6c97ddc1/image?mode=full-fit&client=16f85345-9f3c-42b3-b4b6-87f77705a934&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxNmY4NTM0NS05ZjNjLTQyYjMtYjRiNi04N2Y3NzcwNWE5MzQiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmMzNGNkMzM3LTJhNGItNDM2MS1hNWNkLWFlNWE2Yzk3ZGRjMSI6WyJyZWFkIl19LCJleHAiOjE1MDExNzMwMzYsIm5iZiI6MTUwMTE2OTY3Nn0.FzhmzqBSHOcip93t_-1dk2HQMPYUSpVEIkp2OzuSC28
      text: |
        Team:   $BUILD_TEAM_NAME
        Job:    $BUILD_JOB_NAME
        Build:  $BUILD_NAME.$BUILD_ID'
  on_failure:
    put: slack-alert
    params:
      text: "bashlib: Test failed"
