---
resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true

jobs:
- name: test
  public: true
  max_in_flight: 1
  plan:
  - get: resource-bashlib
    trigger: true
  - aggregate:
    - task: task-test
      file: resource-bashlib/ci/tasks/task.yml
      params:
        deployment_name: test-alpine
        docker_image_image: "vergissberlin/alpine-development"
        docker_image_tag: "latest"
        docker_image_source: upstream
        DISTRIBUTION: {repository: vergissberlin/ubuntu-development}
