---
resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true

jobs:
- name: test
  public: true
  plan:
  - get: resource-bashlib
    trigger: true
  - aggregate:
    - task: task-test
      file: resource-bashlib/ci/tasks/test-alpine.yml
    - task: task-test
      file: resource-bashlib/ci/tasks/test-centos.yml
    - task: task-test
      file: resource-bashlib/ci/tasks/test-debian.yml
    - task: task-test
      file: resource-bashlib/ci/tasks/test-fedora.yml
    - task: task-test
      file: resource-bashlib/ci/tasks/test-opensuse.yml
    - task: task-test
      file: resource-bashlib/ci/tasks/test-ubuntu.yml
