---
resources:
- name: resource-bashlib
  type: git
  source:
    uri: https://github.com/vergissberlin/bashlib.git
    branch: master
    disable_ci_skip: true

jobs:
- name: test-alpine
  public: true
  plan:
  - get: resource-bashlib
    trigger: true
  - aggregate:
    - task: task-test
      file: resource-bashlib/ci/tasks/test-alpine.yml
- name: test-debian
  public: true
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-alpine]
  - aggregate:
    - task: task-test
      file: resource-bashlib/ci/tasks/test-debian.yml
- name: test-centos
  public: true
  plan:
  - get: resource-bashlib
    trigger: true
    passed: [test-debian]
  - aggregate:
    - task: task-test
      file: resource-bashlib/ci/tasks/test-centos.yml
